### ISSUE TITLE
Adopt to google sheets

### ISSUE THREAD

**Issue by iLLiac4** [openhomeautomation/esp8266-cloud#1]
Hi. I am trying to adopt something similar to the google docs an i am having a little problems.
So i basically took this code and mode it a little https://github.com/iLLiac4/wifi-weather-sensor it is using  sparkfun as data input. I would like to use google docs like described here http://www.instructables.com/id/Post-to-Google-Docs-with-Arduino/?ALLSTEPS
Would it be possible to adopt the code from my git ti the google docs on an easy way?

TNX

**Comment by marcoschwartz** [comment]
Hi,

Looks like a great project you have here! The best way for Google Docs would be to use Temboo:

https://www.temboo.com/library/

However I never tested it on the ESP8266, so you'd need to modify the CC3000 Arduino example for it to work. Good luck! (and closing this as it's not an issue :) )

**Comment by electronicsguy** [comment]
@iLLiac4  @marcoschwartz  I have published my project which uses a direct link from esp8266 (HTTPS requests with forwarding) to Google directly. No need of middlemen like Temboo or pushingbox. You can check it out here: [HTTPSRedirect](https://github.com/electronicsguy/ESP8266/tree/master/HTTPSRedirect).
